---
name: sandman
version: 0.2.0.0
github: abhinav/sandman
author: Abhinav Gupta
maintainer: Abhinav Gupta <mail@abhinavg.net>
license: MIT
category: Development
copyright: (c) 2016 Abhinav Gupta
synopsis: Manages Cabal sandboxes to avoid rebuilding packages.
description: |
  sandman aims to reduce the amount of time spent rebuilding commonly used
  Hackage packages by managing a global set of Cabal sandboxes that can be
  mixed into any project's Cabal sandbox.

  For more information, check the
  <https://github.com/abhinav/sandman/blob/master/README.md README>.
extra-source-files:
  - README.md
  - CHANGES.md

ghc-options: -Wall

executables:
  sandman:
    main: Main.hs
    source-dirs: src
    dependencies:
      - base >= 4.7 && < 5
      - Cabal
      - containers >= 0.5
      - directory >= 1.2
      - filepath >= 1.3
      - optparse-applicative >= 0.11
      - process >= 1.2
      - text >= 1.2
      - unix-compat >= 0.4
